### PR TITLE
Add GQX and AMM contract .json 's

### PR DESCRIPTION
**Pull request by tacticalnoot**
Added GQX and AMM assets

### CODE REVIEW

**Comment by esteblock** [comment]
@tacticalnoot 
GQX: https://stellar.expert/explorer/public/asset/GQX-GD7TC72O5HML5UMZXQCIXGBR4KJ3MYM2ICPOR4BBN56K6JUSRVWTDAQF

**Review by esteblock — APPROVED** [review]
Hello @tacticalnoot we are good gor GQX,
However AMM will be rejected by our github action checker because the contract you placed in the list is:
https://stellar.expert/explorer/public/contract/CDHBIACXSM5K2NFCCHQIJQNDJPHGPW4OHIYVXGCFMVT7PNLWXY4NGRNH
And is linked with asset https://stellar.expert/explorer/public/asset/AMM-GARQ7O5JPBD2DDVEFFZ2LVWH77BYSC7K7RMGI7W5GLRVSWPHZBNGBDOQ
But in the json is https://stellar.expert/explorer/public/asset/AMM-GD7TC72O5HML5UMZXQCIXGBR4KJ3MYM2ICPOR4BBN56K6JUSRVWTDAQF

Also, the toml URL of GQX is in small letters, but you in the json placed big letters.

**Comment by esteblock** [comment]
In fact, in order to bulletproof our system, I'll try to accet the PR and we will see that it will be rejected @TacticalNoot | noot.xlm

**Comment by tacticalnoot** [comment]
I will get this sorted today! Thank you for your patience! On Apr 6, 2024, at 10:33 AM, Esteban Iglesias ***@***.***> wrote:﻿
@esteblock approved this pull request.

Hello @tacticalnoot we are good gor GQX,
However AMM will be rejected by our github action checker because the contract you placed in the list is:
https://stellar.expert/explorer/public/contract/CDHBIACXSM5K2NFCCHQIJQNDJPHGPW4OHIYVXGCFMVT7PNLWXY4NGRNH
And is linked with asset https://stellar.expert/explorer/public/asset/AMM-GARQ7O5JPBD2DDVEFFZ2LVWH77BYSC7K7RMGI7W5GLRVSWPHZBNGBDOQ
But in the json is https://stellar.expert/explorer/public/asset/AMM-GD7TC72O5HML5UMZXQCIXGBR4KJ3MYM2ICPOR4BBN56K6JUSRVWTDAQF
Also, the toml URL of GQX is in small letters, but you in the json placed big letters.

**Pull request merged**
